// Data QA report. Reads the curated site CSVs and the built public/data, and writes
//   data/build/qa-report.md      human-readable report
//   data/build/recall-queue.csv  rows still needing sources, worst first (the verification work list)
// Never fails the build: hard errors belong in validate-data.ts.
import { mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { parse as parseCsv } from "csv-parse/sync";
import type { Entity, FeatureProps, Source } from "../src/types.ts";
import { BCE_BREAKS } from "../src/time/scale.ts";
import { distanceKm, normaliseLabel, outliers, siteStatus, windowMatchesText, type Status } from "./lib/qa.ts";

const OUT = "data/build";
const DUP_KM = 1; // recalled coords are ~2 dp; real neighbouring sites (e.g. Swartkrans–Kromdraai) are further apart

interface Row {
  file: string;
  line: number;
  entity_id: string;
  label: string;
  lat: number;
  lon: number;
  start_year: number;
  end_year: number;
  date_text: string;
  confidence: string;
  source_id: string;
  wikidata: string;
  coord_source: string;
  date_source: string;
  notes: string;
  status: Status;
  issues: string[];
}

const rows: Row[] = [];
for (const file of ["species-sites.csv", "culture-sites.csv"]) {
  const recs = parseCsv(readFileSync(`data/curated/${file}`, "utf8"), { columns: true, skip_empty_lines: true }) as Record<string, string>[];
  recs.forEach((r, i) =>
    rows.push({
      file,
      line: i + 2,
      entity_id: r.entity_id,
      label: r.label ?? "",
      lat: Number(r.lat),
      lon: Number(r.lon),
      start_year: Number(r.start_year),
      end_year: Number(r.end_year),
      date_text: r.date_text ?? "",
      confidence: r.confidence ?? "",
      source_id: r.source_id,
      wikidata: r.wikidata ?? "",
      coord_source: r.coord_source ?? "",
      date_source: r.date_source ?? "",
      notes: r.notes ?? "",
      status: siteStatus(r as never),
      issues: [],
    }),
  );
}
const entities: Entity[] = JSON.parse(readFileSync("public/data/entities.json", "utf8"));
const features: { properties: FeatureProps }[] = JSON.parse(readFileSync("public/data/features.geojson", "utf8")).features;
const sources: Source[] = JSON.parse(readFileSync("public/data/sources.json", "utf8"));
const byEntity = new Map<string, Row[]>();
for (const r of rows) (byEntity.get(r.entity_id) ?? byEntity.set(r.entity_id, []).get(r.entity_id)!).push(r);
const where = (r: Row) => `${r.file}:${r.line}`;
const md: string[] = [];
const section = (title: string, lines: string[], empty = "None.") => md.push(`\n## ${title}\n`, ...(lines.length ? lines : [empty]));

// ---------- per-row checks ----------
for (const r of rows) {
  const ok = windowMatchesText(r.start_year, r.end_year, r.date_text);
  if (ok === false) r.issues.push("date window does not contain date_text");
  if (ok === undefined && r.date_text) r.issues.push("date_text not machine-readable");
  if (r.status === "partial") {
    if (!r.coord_source) r.issues.push("no coord_source");
    if (!r.date_source) r.issues.push("no date_source");
    if (r.coord_source && r.date_source && r.source_id === "recall") r.issues.push("evidence complete: switch source_id from recall");
  }
}

// Duplicates within an entity: same normalised label, or closer than DUP_KM.
const dupLines: string[] = [];
for (const [id, list] of byEntity)
  for (let i = 0; i < list.length; i++)
    for (let j = i + 1; j < list.length; j++) {
      const a = list[i], b = list[j];
      const km = distanceKm(a.lat, a.lon, b.lat, b.lon);
      const sameLabel = normaliseLabel(a.label) === normaliseLabel(b.label);
      if (!sameLabel && km >= DUP_KM) continue;
      const why = sameLabel ? "same label" : `${km.toFixed(1)} km apart`;
      dupLines.push(`- \`${id}\`: "${a.label}" (${where(a)}) and "${b.label}" (${where(b)}), ${why}`);
      a.issues.push(`possible duplicate of ${b.label}`);
      b.issues.push(`possible duplicate of ${a.label}`);
    }

// Geographic outliers per entity.
const outLines: string[] = [];
for (const [id, list] of byEntity)
  for (const i of outliers(list)) {
    outLines.push(`- \`${id}\`: "${list[i].label}" (${where(list[i])}) at ${list[i].lat}, ${list[i].lon}`);
    list[i].issues.push("far from the entity's other sites");
  }

// ---------- summary ----------
const statusCount = (cat: string, s: Status) => rows.filter((r) => r.file.startsWith(cat) && r.status === s).length;
md.push(
  "# Data QA report",
  "",
  `Generated by \`npm run data:report\` on ${new Date().toISOString().slice(0, 10)}. Work list: \`data/build/recall-queue.csv\`.`,
  "",
  "| Sites | recall (unchecked) | partial | sourced | total |",
  "|---|---|---|---|---|",
  ...["species", "culture"].map((c) => {
    const [a, b, d] = (["recall", "partial", "sourced"] as Status[]).map((s) => statusCount(c, s));
    return `| ${c} | ${a} | ${b} | ${d} | ${a + b + d} |`;
  }),
);
const conf = ["low", "medium", "high"].map((c) => `${c} ${rows.filter((r) => r.status !== "sourced" && r.confidence === c).length}`);
md.push("", `Unsourced rows by stated confidence: ${conf.join(", ")}.`);

// ---------- entities ----------
const nonGroup = entities.filter((e) => !e.group);
const withFeatures = new Set(features.map((f) => f.properties.entity_id));
section(
  "Entities with no features",
  nonGroup.filter((e) => !withFeatures.has(e.id)).map((e) => `- \`${e.id}\` (${e.category})`),
);
const isSite = (e: { category: string }) => e.category === "species" || e.category === "culture";
const recallOnly = nonGroup.filter((e) => isSite(e) && (byEntity.get(e.id) ?? []).every((r) => r.status !== "sourced"));
section(
  "Entities with no sourced sites",
  recallOnly.length
    ? [
        `${recallOnly.length} of ${nonGroup.filter(isSite).length} species/culture entities. Their spans in entities.yaml are`,
        "derived from unsourced rows, so the validator's \"site within entity span\" check can't catch errors for them yet.",
        "",
        recallOnly.map((e) => `\`${e.id}\``).join(", "),
      ]
    : [],
);

// ---------- row issues ----------
section("Possible duplicate sites (same entity)", dupLines);
section("Geographic outliers (check, may be genuine)", outLines);
const dateBad = rows.filter((r) => r.issues.some((i) => i.startsWith("date")));
section("Date window vs date_text", dateBad.map((r) => `- ${where(r)} \`${r.entity_id}\` "${r.label}": ${r.issues.filter((i) => i.startsWith("date")).join("; ")} (text "${r.date_text}", window ${r.start_year}..${r.end_year})`));
section("Partly sourced rows", rows.filter((r) => r.status === "partial").map((r) => `- ${where(r)} "${r.label}": ${r.issues.join("; ")}`));

// ---------- attribution ----------
const used = new Map<string, number>();
for (const f of features) used.set(f.properties.source_id, (used.get(f.properties.source_id) ?? 0) + 1);
section(
  "Sources and attribution",
  sources.map((s) => {
    const flags = [];
    if (!s.licence || /^n\/?a$/i.test(s.licence)) flags.push("no licence (not a real source)");
    if (!s.citation) flags.push("no citation");
    return `- \`${s.id}\`: ${used.get(s.id) ?? 0} features, ${s.licence}${flags.length ? ` **(${flags.join(", ")})**` : ""}`;
  }),
);

// ---------- coverage by slider segment ----------
const seg: string[] = ["| Segment (years BCE) | species sites (sourced) | culture sites (sourced) | civilization features |", "|---|---|---|---|"];
for (let i = 0; i < BCE_BREAKS.length - 1; i++) {
  const lo = 1 - BCE_BREAKS[i], hi = 1 - BCE_BREAKS[i + 1];
  const inSeg = (s: number, e: number) => s < hi && e >= lo;
  const fmt = (n: number) => (n >= 1e6 ? `${n / 1e6} Ma` : n >= 1e3 ? `${n / 1e3} ka` : `${n}`);
  const site = (cat: string) => {
    const list = rows.filter((r) => r.file.startsWith(cat) && inSeg(r.start_year, r.end_year));
    return `${list.length} (${list.filter((r) => r.status === "sourced").length})`;
  };
  const civ = features.filter((f) => f.properties.category === "civilization" && inSeg(f.properties.start_year, f.properties.end_year)).length;
  seg.push(`| ${fmt(BCE_BREAKS[i])} to ${BCE_BREAKS[i + 1] ? fmt(BCE_BREAKS[i + 1]) : "1 CE"} | ${site("species")} | ${site("culture")} | ${civ} |`);
}
section("Coverage by slider segment", seg);

// ---------- size budget ----------
const gz = gzipSync(readFileSync("public/data/features.geojson")).length;
section("Size", [
  `features.geojson: ${(statSync("public/data/features.geojson").size / 1e6).toFixed(2)} MB raw, ${(gz / 1e6).toFixed(2)} MB gzipped (budget 5 MB gzipped).`,
]);

// ---------- write ----------
mkdirSync(OUT, { recursive: true });
writeFileSync(`${OUT}/qa-report.md`, md.join("\n") + "\n");
const rank: Record<string, number> = { low: 0, medium: 1, high: 2 };
const queue = rows
  .filter((r) => r.status !== "sourced")
  .sort((a, b) => (rank[a.confidence] ?? 0) - (rank[b.confidence] ?? 0) || b.issues.length - a.issues.length || a.entity_id.localeCompare(b.entity_id));
const q = (v: string | number) => (/[",\n]/.test(String(v)) ? `"${String(v).replace(/"/g, '""')}"` : String(v));
writeFileSync(
  `${OUT}/recall-queue.csv`,
  ["file,line,entity_id,label,lat,lon,date_text,confidence,status,missing,issues"]
    .concat(
      queue.map((r) =>
        [r.file, r.line, r.entity_id, r.label, r.lat, r.lon, r.date_text, r.confidence, r.status,
          [!r.coord_source && "coords", !r.date_source && "dates"].filter(Boolean).join("+"), r.issues.join("; ")].map(q).join(","),
      ),
    )
    .join("\n") + "\n",
);

console.log(`QA: ${rows.length} sites — ${rows.filter((r) => r.status === "sourced").length} sourced, ${rows.filter((r) => r.status === "partial").length} partial, ${rows.filter((r) => r.status === "recall").length} recall`);
console.log(`    ${dupLines.length} possible duplicates, ${outLines.length} outliers, ${dateBad.length} date issues, ${nonGroup.filter((e) => !withFeatures.has(e.id)).length} empty entities`);
console.log(`    wrote ${OUT}/qa-report.md and ${OUT}/recall-queue.csv`);
